### PR TITLE
ISSUE-91: Adding duration for the LOI.

### PR DESCRIPTION
**Pull request by mathjert**
Adding duration of studies to the LOI-element. This is to satisfy the needs of issue 91. 
https://github.com/emrex-eu/elmo-schemas/issues/91

### CODE REVIEW

**Comment by mathjert** [comment]
Change to `<duration type="day">3</duration>`

**Review by geirmv — CHANGES_REQUESTED** [review]
As your commented @mathjert : Change to `<duration type="day">3</duration>`

**Comment by mathjert** [comment]
Will change to use the XML-duration type instead

**Comment by mathjert** [comment]
is this the correct notation?

**Comment by mirkostanic** [comment]
Yes it's correct but it is not the easiest notation to use.
For example 8 hours is written as PT8H. Not very human readable but I suppose it does not need to be for an XML.

**Review by mirkostanic — APPROVED** [review]
Technically correct. Only open question is business related.

**Comment by geirmv** [comment]
We had the same discussion internally on xml duration type which is not very reader friendly. It is however (maybe a bit to much) flexible and standardized. The alternative was to set up our own way of describing different types of duration.

**Review by geirmv — APPROVED** [review]

**Pull request merged**
